### ISSUE TITLE
File seems to be closed when trying to index

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2320]
Yes @JoanFM, using the prefetch argument in the flow-config solved the original problem. I tried to pass the batch_size and the request_size like you, but I still get the same error. I have some additional logs, which might indicate what causes the problem. As I said, the first few batches are indexed successfully, but at some point I get this error:

```
        encoder@63[I]:no update since 2021-04-10 07:38:17, will not save. If you really want to save it, call "touch()" before "save()" to force saving
        encoder@63[I]:#sent: 3 #recv: 4 sent_size: 13.8 MB recv_size: 1.2 MB
      chunk_idx@66[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime▸⚐
        encoder@63[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸⚐
   NumpyIndexer@66[S]:artifacts of this executor (wrap_idx) is persisted to /var/huforce/fs/workspace/wrap_idx-0/wrap_idx.bin
BinaryPbIndexer@66[S]:artifacts of this executor (chunk_idx) is persisted to /var/huforce/fs/workspace/chunk_idx-0/chunk_idx.bin
      chunk_idx@66[I]:no update since 2021-04-10 07:38:17, will not save. If you really want to save it, call "touch()" before "save()" to force saving
      chunk_idx@66[I]:#sent: 3 #recv: 4 sent_size: 1.9 MB recv_size: 15.6 MB
        doc_idx@67[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime▸doc_idx/ZEDRuntime▸⚐
DEBUG | Message: Successfully indexed 4 documents!
        doc_idx@67[S]:artifacts of this executor (doc_idx_file) is persisted to /var/huforce/fs/workspace/doc_idx_file-0/doc_idx_file.bin
        doc_idx@67[I]:#sent: 3 #recv: 4 sent_size: 6.3 KB recv_size: 2.2 MB
       | 📃     16 ⏱️ 262.9s 🐎 0.1/s      4   requests        gateway@72[I]:send: 5 recv: 4 pending: 1
        crafter@60[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸⚐
DEBUG | Message: File-Info: research_admission.txt
DEBUG | Message: File-Info: cloudcomputing.pptx
DEBUG | Message: File-Info: WS_2012_White_Paper_Hyper-V.pdf
DEBUG | Message: File-Info: writing-sql-queries.docx
        crafter@60[I]:no update since 2021-04-10 07:38:17, will not save. If you really want to save it, call "touch()" before "save()" to force saving
        crafter@60[I]:#sent: 5 #recv: 6 sent_size: 1.2 MB recv_size: 5.2 KB
        encoder@63[I]:#sent: 4 #recv: 5 sent_size: 15.6 MB recv_size: 1.2 MB
      chunk_idx@66[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime▸⚐
        encoder@63[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸⚐
      chunk_idx@66[I]:#sent: 4 #recv: 5 sent_size: 2.2 MB recv_size: 16.1 MB
DEBUG | Message: Encoding 552 paragraphs
      chunk_idx@66[E]:ValueError('write to closed file')
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 198, in _msg_callback
    self._zmqlet.send_message(self._callback(msg))
  File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 184, in _callback
    self._pre_hook(msg)._handle(msg)._post_hook(msg)
  File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 177, in _handle
    self._executor(self.request_type)
  File "/usr/local/lib/python3.8/site-packages/jina/executors/__init__.py", line 595, in __call__
    d()
  File "/usr/local/lib/python3.8/site-packages/jina/drivers/__init__.py", line 381, in __call__
    self._apply_all(documents, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jina/drivers/index.py", line 58, in _apply_all
    self.exec_fn(keys, values)
  File "/usr/local/lib/python3.8/site-packages/jina/executors/decorators.py", line 44, in arg_wrapper
    f = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/keyvalue.py", line 178, in add
    self.write_handler.header.write(
ValueError: write to closed file
        doc_idx@67[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime✖▸doc_idx/ZEDRuntime▸⚐
dev_ai            | DEBUG | Message: Successfully indexed 4 documents!
```
What's also strange is, that the failed documents for the chunk-idx are passed on to the doc-idx, as you can see in the logs.

My flow for indexing:
```
!AsyncFlow
with:
  logserver: false
  show-exc-info: true
  prefetch: 2
  # request-size: 2
  # batch_size: 2
pods:
  crafter:
    uses: pods/craft.yml
  encoder:
    uses: pods/encode.yml
    timeout_ready: 600000
  chunk_idx:
    uses: pods/chunk.yml
  doc_idx:
    uses: pods/doc.yml
```

_Originally posted by @nero-nazok in https://github.com/jina-ai/jina/issues/2298#issuecomment-817084516_

**Comment by JoanFM** [comment]
Issue opened from #2298, see the comments there for further details

**Comment by cristianmtr** [comment]
Original comment [here](https://github.com/jina-ai/jina/issues/2298#issuecomment-823114529) by @nero-nazok

> @JoanFM Yes the delete-driver is used, but shouldn't be the cause of our problem. We index large text documents. I asked my colleague @janandreschweiger for sharing the documents.
> 
> @cristianmtr I index my text documents like so:
> ```
> def input_fn():
>     for sharepoint_file in iter_sharepoint():
>         return Document(id=sharepoint_file['id'], uri=sharepoint_file['uri'])
> 
> with Flow.load_config('./index-flow.yml') as f:
>     f.index(input_fn, batch_size=2, request_size=2)
> ```

so you're not assigning any content to the Document, just an id and a uri?

**Comment by JoanFM** [comment]
hey @nero-nazok,

Can you add a `print` of the `Document` arriving with the `last` indexed document? Also do you have the full logs of the indexing?

Without the information from the `crafter` we cannot now how to access the `uri` provided in input

**Comment by cristianmtr** [comment]
@nero-nazok @janandreschweiger

Can you perhaps send us a toy subset of your code that is a minimal reproducible unit? You can send it via email (cristian.mitroi at jina dot ai) or DM us on our community Slack https://slack.jina.ai/

**Comment by nero-nazok** [comment]
@JoanFM, @cristianmtr I have an important meeting now. I will provide you with all this information in the afternoon. Thank you!

**Comment by JoanFM** [comment]
Hey @nero-nazok , now I realize, your `input_fn` is not a `generator` but it just returns a single `Document`. Could that be the reason? Can you try turning that into a `generator`?

**Comment by JoanFM** [comment]
Could you also share some details about the implementation of `iter_sharepoint()`?

**Comment by nero-nazok** [comment]
No sorry @JoanFM, that was a mistake from my side. I just simplified our logic.

**Comment by nero-nazok** [comment]
@JoanFM & @cristianmtr I made some tests and it's really strange:
I have 29 documents
- Indexing the first 8 documents works fine
- Indexing the remaining 19 documents also works fine
- Indexing all 29 documents at once fails

**Comment by nero-nazok** [comment]
@JoanFM, @cristianmtr I have talked to @janandreschweiger. Unfortunately, I cannot share all the requested code. Nevertheless, if you want to take a look, @janandreschweiger could schedule a call with you and would show you the code and the issue.

**Comment by JoanFM** [comment]
Hey @nero-nazok ,

that would be good. can you contact in the community slack channel?

**Comment by nero-nazok** [comment]
Sure @JoanFM, @janandreschweiger wants to do that.

**Comment by JoanFM** [comment]
I have created this small system to try to reproduce the issue but could not succeed:

```
from jina.flow import Flow
from jina import Document
import asyncio

def iter_sharepoint():
    a = []
    for i in range(10000):
        a.append({'id': f'{i}', 'text': 'Hey here I am'})

    return a

async def input_fn():
    print(f' hey here Joan')
    for sharepoint_file in iter_sharepoint():
        print(f' sharepoint_file {sharepoint_file}')
        yield Document(id=sharepoint_file['id'], text=sharepoint_file['text'])


async def work():
    with Flow.load_config('./flow.yml') as f:
        print(f' ieee')
        async for r in f.index(inputs=input_fn, request_size=2):
            pass

loop = asyncio.get_event_loop()
loop.run_until_complete(work())
loop.close()

```

with a `flow.yml` as :

```
!AsyncFlow
with:
  show-exc-info: true
  prefetch: 2
pods:
  crafter:
    uses: pods/craft.yml
  encoder:
    uses: pods/encode.yml
    timeout_ready: 600000
  chunk_idx:
    uses: pods/chunk.yml
  doc_idx:
    uses: pods/doc.yml
```

and pods:
craft.yml:
```
!Sentencizer
```
encode.yml
```
!TransformerTorchEncoder
with:
  pooling_strategy: 'cls'
  pretrained_model_name_or_path: distilbert-base-cased
  max_length: 96
#metas:
#  on_gpu: true
requests:
  on:
    ControlRequest:
      - !ControlReqDriver {}
    [SearchRequest, TrainRequest, IndexRequest]:
      - !EncodeDriver
        with:
          traversal_paths: ['c']
```

chunk_idx.yml
```
!CompoundIndexer
components:
  - !NumpyIndexer
    with:
      index_filename: vec.gz
      delete_on_dump: true
    metas:
      name: wrap_idx
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
      delete_on_dump: true
    metas:
      name: chunk_idx
metas:
  name: chunk_compound_idx
requests:
  on:
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: wrap_idx
          traversal_paths: ['c']  # c...chunks (= sentence vectors)
      - !ExcludeQL
        with:
          traversal_paths: ['c']
          fields: embedding
      - !KVIndexDriver
        with:
          executor: chunk_idx
          traversal_paths: ['c']
    SearchRequest:
      - !VectorSearchDriver
        with:
          executor: wrap_idx
      - !KVSearchDriver
        with:
          executor: chunk_idx
          traversal_paths: ['m']
```

doc.yml
```
!BinaryPbIndexer
with:
  index_filename: doc.gz
  delete_on_dump: true
metas:
  name: doc_idx
requests:
  on:
    IndexRequest:
      - !KVIndexDriver
        with:
          traversal_paths: ['r']
    SearchRequest:
      - !KVSearchDriver
        with:
          executor: doc_idx
          traversal_paths: ['m']
```

Does it map to more or less ur pipeline?

**Comment by JoanFM** [comment]
Recap from our findings:

Setting `dump_interval: 9999999` to a very large number in the `flow.yml` solves the issue. Which shows that we have a bug in our `dumping` logic in the `BinaryPbIndexer` where we may not be catching exceptions or may not be properly handling `file handlers`

**Comment by JoanFM** [comment]
@janandreschweiger ,

Could you try again to remove the `dump_interval` configuration and try with the `delete_on_dump: false`? I want to try to see if we did not remove workspace properly before trying that option? The 2 options are linked to each other, and knowing this would help us identify the issue better

**Comment by janandreschweiger** [comment]
Sure @JoanFM.

**Comment by janandreschweiger** [comment]
I have some bad news @JoanFM. I tried indexing again a few times and it doesn't work anymore. I think that the dump_interval configuration just delayed the error somehow. And we didn't wait long enough.

I discovered however one thing: The indexing fails at the exact same document pair. There is nevertheless nothing special about these documents. There also are much larger ones that are indexed correctly. I have also tried setting a batch_size for the chunk-indexer. Nothing changes. I will exclude this pair and see if it works.

**Comment by JoanFM** [comment]
> I have some bad news @JoanFM. I tried indexing again a few times and it doesn't work anymore. I think that the dump_interval configuration just delayed the error somehow. And we didn't wait long enough.
> 
> I discovered however one thing: The indexing fails at the exact same document pair. There is nevertheless nothing special about these documents. There also are much larger ones that are indexed correctly. I have also tried setting a batch_size for the chunk-indexer. Nothing changes. I will exclude this pair and see if it works.

Indexing only that pair also makes the Flow crash?

**Comment by janandreschweiger** [comment]
@JoanFM I don't think so, but I will give it a try

**Comment by janandreschweiger** [comment]
Yes @JoanFM it works. Indexing normally fails at 12th document. But when I index all documents except the first 4 ([4:]), I don't get any errors.

**Comment by janandreschweiger** [comment]
@JoanFM :D ok so now everything works. I got the same error for the doc-indexer (not the chunk-indexer) and didn't realize that. I just had to set delete_on_dump to false for the doc-indexer as well and everything works. Thanks for all your help!!!

**Comment by JoanFM** [comment]
Ok, so u confirm that the problem comes from the delete on dump right? it would align with my suspicions

**Comment by janandreschweiger** [comment]
Yes @JoanFM

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

I am not sure, but would it be possible for you to try to run the same example (with `delete_on_dump`) activated on the branch of PR #2322?

 I could not test with your case, but maybe it can solve the problem.

**Comment by janandreschweiger** [comment]
Sure I will do that @JoanFM. Thank you!

**Comment by JoanFM** [comment]
The PR is merged @janandreschweiger and should fix this specific issue, because we managed to reproduce and add a test

**Comment by janandreschweiger** [comment]
Thanks @JoanFM for your effort. Unfortunately, the PR didn't resolve our issue. I just tested the PR by installing the master like so: `pip install git+https://github.com/jina-ai/jina.git@master` and checked the version.

My error log:
```
dev_ai            |       chunk_idx@184[I]:#sent: 5 #recv: 6 sent_size: 1.9 MB recv_size: 13.9 MB
dev_ai            |       chunk_idx@184[E]:ValueError('write to closed file')
dev_ai            |  add "--quiet-error" to suppress the exception details
dev_ai            | Traceback (most recent call last):
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 198, in _msg_callback
dev_ai            |     self._zmqlet.send_message(self._callback(msg))
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 184, in _callback
dev_ai            |     self._pre_hook(msg)._handle(msg)._post_hook(msg)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 177, in _handle
dev_ai            |     self._executor(self.request_type)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/__init__.py", line 573, in __call__
dev_ai            |     d()
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/drivers/__init__.py", line 390, in __call__
dev_ai            |     self._apply_all(documents, *args, **kwargs)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/drivers/index.py", line 72, in _apply_all
dev_ai            |     self.exec_fn(keys, values)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/decorators.py", line 45, in arg_wrapper
dev_ai            |     f = func(self, *args, **kwargs)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/keyvalue.py", line 250, in add
dev_ai            |     self._add(keys, values)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/keyvalue.py", line 132, in _add
dev_ai            |     writer.header.write(
dev_ai            | ValueError: write to closed file
dev_ai            |         doc_idx@189[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime✖▸doc_idx/ZEDRuntime▸⚐
dev_ai            |         doc_idx@189[I]:#sent: 5 #recv: 6 sent_size: 7.1 KB recv_size: 1.9 MB
dev_ai            |         doc_idx@189[E]:ValueError('write to closed file')
dev_ai            |  add "--quiet-error" to suppress the exception details
dev_ai            | Traceback (most recent call last):
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 198, in _msg_callback
dev_ai            |     self._zmqlet.send_message(self._callback(msg))
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 184, in _callback
dev_ai            |     self._pre_hook(msg)._handle(msg)._post_hook(msg)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 177, in _handle
dev_ai            |     self._executor(self.request_type)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/__init__.py", line 573, in __call__
dev_ai            |     d()
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/drivers/__init__.py", line 390, in __call__
dev_ai            |     self._apply_all(documents, *args, **kwargs)
dev_ai            |   File "/var/huforce/src/src/jina/pods/doc/other/file/index_driver.py", line 37, in _apply_all
dev_ai            |     self.exec_fn(keys, values)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/decorators.py", line 45, in arg_wrapper
dev_ai            |     f = func(self, *args, **kwargs)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/keyvalue.py", line 250, in add
dev_ai            |     self._add(keys, values)
dev_ai            |   File "/usr/local/lib/python3.8/site-packages/jina/executors/indexers/keyvalue.py", line 132, in _add
dev_ai            |     writer.header.write(
dev_ai            | ValueError: write to closed file
```
Have you any idea what could possibly go wrong? In my opinion the delete_on_dump option could be completely ignored when indexing.

I also came across another small issue in the master-branch. The content that is passed to the encode method is no longer a np.array, but a list. So you either need to revert this behavior or change the typing:
```
class SentenceEncoder(BaseEncoder):
    def encode(self, content: 'np.ndarray', *args, **kwargs) -> 'np.ndarray':
        print(type(content)) # 'list' not 'np.array'
```

**Comment by JoanFM** [comment]
That is very weird, because I managed to reproduce and added a test. Could you try again making sure that in ur installed code u have the changes u see on the PR #2322?

As per the Encoder thing, can you try changing the 'np.ndarray' type annotation to np.ndarray (whithout the string)? We are iterating on our Executor API and trying to help the user by providing type sniffing. However, we do not know if it will be kept that way.

**Comment by JoanFM** [comment]
@janandreschweiger 

There must be some problem, because the linenumbers showing in your logs, do not match the line numbers in the current master, so I guess it is not yet tested.

Due to this Executor API unstability, I would still not recommend you to migrate to newest version, but would still be good to know if this would solve the issue. (You could go on with just having a negative `dump_interval` or too large to even care.

**Comment by janandreschweiger** [comment]
Hi @JoanFM, I will try out the new 1.1.10 version today.

**Comment by janandreschweiger** [comment]
Hey @JoanFM I tried it yesterday and everything worked. Thank you @JoanFM. Awesome.
